r"""Body / paragraph / run / table walking for the docx adapter.

Converts the OOXML ``w:body`` subtree into IR blocks: paragraphs,
headings, lists, tables, and standalone display-math blocks. Inline
math is surfaced as a text island embedded in the surrounding
paragraph: inline OMML and Word EQ fields as *deferred* source-tagged
islands (:mod:`brailix.core.inline_math`, converted later by the
frontend's math pass), and OLE MathType (MTEF) as an eagerly-decoded
``$<math>...</math>$`` island — MTEF is binary, which the text IR can't
carry, so it is decoded at the input boundary. See the package
``__init__`` "Math handling" note.

DAG position: depends on :mod:`._xml` (tag / serialisation helpers and
namespace constants) and :mod:`._ole` (OLE→inline-math extraction).
The orchestration entry points (:func:`parse_docx` etc.) live in the
package ``__init__`` and call into here.
"""

from __future__ import annotations

import re

from brailix.core import inline_math
from brailix.input.docx._ole import _ole_object_to_inline_math
from brailix.input.docx._xml import (
    _INLINE_MATH_OPEN,
    _W_PREFIX,
    Element,
    _first,
    _first_local,
    _inline_math_as_text,
    _local,
    _ns_attr,
    _serialize,
)
from brailix.ir.document import (
    Block,
    Heading,
    List,
    ListItem,
    MathBlock,
    Paragraph,
    Table,
    TableCell,
    TableRow,
)

_HEADING_STYLE_RE = re.compile(r"^heading\s*(\d+)$", re.IGNORECASE)

# Word lets a paragraph be a list item via either ``numPr`` (real
# numbering with a definition) or just a list-flavoured pStyle (eg.
# ``ListBullet``, ``ListNumber1``).  The style-only path is common in
# documents generated by python-docx or by Word's "Apply Style"
# command without explicit numbering, so we detect both.  The regex
# below matches the bullet / number / dash / continuation variants
# Word ships out of the box plus their numbered siblings (``ListNumber``,
# ``ListNumber2``, ...).
_LIST_STYLE_RE = re.compile(
    r"^list\s*(bullet|number|dash|paragraph|continue)(\d*)$",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Body walker
# ---------------------------------------------------------------------------


# Block-level wrappers Word places around whole paragraphs / tables.
_TRANSPARENT_BLOCK_WRAPPERS = frozenset(
    {"ins", "del", "moveFrom", "moveTo", "customXml"}
)


def _iter_effective_body_children(parent: Element):
    """Yield the block-level children of ``parent`` in document order,
    descending transparently through revision-tracking and content-control
    wrappers Word can place around whole paragraphs / tables.

    ``<w:ins>`` / ``<w:del>`` / ``<w:moveFrom>`` / ``<w:moveTo>`` /
    ``<w:customXml>`` hold their blocks directly; a block-level ``<w:sdt>``
    (content control) holds them under ``<w:sdtContent>``. Without this a
    tracked-changes or content-control wrapped paragraph would be silently
    dropped (the old ``else: continue`` in :func:`_iter_body_blocks`).
    """
    for child in parent:
        tag = _local(child.tag)
        if tag in _TRANSPARENT_BLOCK_WRAPPERS:
            yield from _iter_effective_body_children(child)
        elif tag == "sdt":
            content = _first_local(child, "sdtContent")
            if content is not None:
                yield from _iter_effective_body_children(content)
        else:
            yield child


def _iter_body_blocks(
    body: Element,
    *,
    ole_blobs: dict[str, bytes] | None = None,
    chem_detection: bool = False,
):
    """Yield IR blocks from ``w:body`` in document order.

    Consecutive list-item paragraphs are merged into one :class:`List`
    so the IR matches what users see in Word (no per-line ``List``
    wrapper). Tables and standalone math paragraphs are emitted as
    they appear.

    ``ole_blobs`` maps relationship ids to the raw bytes of every OLE
    object in the package — used to resolve ``<w:object>`` MathType /
    Equation 3.0 formulas to their MTEF payload. ``None`` skips OLE
    handling entirely (kept for callers that build a body element
    outside of :func:`parse_docx`).
    """
    if ole_blobs is None:
        ole_blobs = {}
    pending_list: list[ListItem] = []
    pending_list_ordered: bool | None = None

    def flush_list():
        nonlocal pending_list, pending_list_ordered
        if pending_list:
            yield List(
                ordered=bool(pending_list_ordered),
                items=pending_list,
            )
            pending_list = []
            pending_list_ordered = None

    for child in _iter_effective_body_children(body):
        tag = _local(child.tag)
        if tag == "p":
            blocks = _convert_paragraph(
                child, ole_blobs=ole_blobs, chem_detection=chem_detection
            )
            for blk in blocks:
                if isinstance(blk, ListItem):
                    ordered = blk.id == "__ordered__"
                    blk.id = None  # carrier flag, not a real id
                    if pending_list_ordered is None:
                        pending_list_ordered = ordered
                    elif pending_list_ordered != ordered:
                        # Flavor changed (ordered ↔ unordered) → split.
                        yield from flush_list()
                        pending_list_ordered = ordered
                    pending_list.append(blk)
                else:
                    yield from flush_list()
                    yield blk
        elif tag == "tbl":
            yield from flush_list()
            yield _convert_table(
                child, ole_blobs=ole_blobs, chem_detection=chem_detection
            )
        elif tag == "oMathPara":
            yield from flush_list()
            yield _math_block_from_omath_para(child)
        else:
            # sectPr and unknown elements are ignored — they don't
            # carry braille-relevant content.
            continue
    yield from flush_list()


# ---------------------------------------------------------------------------
# Paragraph → Block
# ---------------------------------------------------------------------------


def _convert_paragraph(
    p: Element,
    *,
    ole_blobs: dict[str, bytes] | None = None,
    chem_detection: bool = False,
) -> list[Block]:
    """Convert a single ``<w:p>`` into one or more IR blocks.

    A paragraph that is **only** display math becomes a standalone
    :class:`MathBlock`. A paragraph mixing text + inline math becomes a
    :class:`Paragraph` (or :class:`Heading` / :class:`ListItem` based
    on style hints). Display-math children inside an otherwise-textual
    paragraph are extracted and emitted between paragraph slices so
    the math still renders as display, not inline.
    """
    if ole_blobs is None:
        ole_blobs = {}
    style = _paragraph_style(p)
    list_info = _paragraph_list_info(p, style=style)
    align = _paragraph_alignment(p)

    # First pass: split the paragraph at display-math boundaries.
    # Word allows ``m:oMathPara`` nested inside ``w:p``; treat each
    # one as a block boundary so display math gets its own block.
    text_parts: list[str] = []
    blocks_out: list[Block] = []

    def flush_text():
        nonlocal text_parts
        if text_parts:
            text = "".join(text_parts).strip()
            if text:
                blocks_out.append(
                    _wrap_text_block(
                        text, style=style, list_info=list_info, align=align
                    )
                )
            text_parts = []

    for run_text, math_block in _walk_paragraph_content(
        p, ole_blobs=ole_blobs, chem_detection=chem_detection
    ):
        if math_block is not None:
            flush_text()
            blocks_out.append(math_block)
        else:
            text_parts.append(run_text)
    flush_text()

    # Empty paragraph: keep an empty Paragraph so the layout reflects
    # the blank line — users sometimes use these as visual spacing.
    if not blocks_out and not style and list_info is None:
        return [Paragraph(text="")]

    return blocks_out


def _wrap_text_block(
    text: str,
    *,
    style: str | None,
    list_info: tuple[int, bool] | None,
    align: str | None = None,
) -> Block:
    """Pick the right block class for a paragraph slice.

    Order of precedence: list info wins over heading style (Word lets
    a "Heading 1" paragraph be a list item — that's still a list item
    in our IR); explicit heading style wins over plain paragraph.

    The list item carries an internal ``__ordered__`` marker via
    :attr:`Block.id` so :func:`_iter_body_blocks` knows what flavour
    of list to wrap it in. The id is cleared before yielding.

    ``align`` (the paragraph's ``w:jc``, already normalised to
    ``"center"`` / ``"right"`` / ``None``) is stamped on whichever block
    kind we produce — recording the source's intent regardless of kind;
    the backend / layout then decide which kinds to honour.
    """
    if list_info is not None:
        _level, ordered = list_info
        item = ListItem(text=text, align=align)
        if ordered:
            item.id = "__ordered__"
        return item
    if style is not None:
        m = _HEADING_STYLE_RE.match(style)
        if m:
            level = int(m.group(1))
            return Heading(level=level, text=text, align=align)
    return Paragraph(text=text, align=align)


def _walk_paragraph_content(
    p: Element,
    *,
    ole_blobs: dict[str, bytes] | None = None,
    chem_detection: bool = False,
):
    """Yield ``(text_piece, math_block | None)`` for each content unit.

    ``text_piece`` is the contribution to surrounding paragraph text
    (empty string when the unit is a standalone display block).
    ``math_block`` is non-None only for display equations
    (``m:oMathPara`` children); inline ``m:oMath`` produces a text piece
    carrying a deferred source-tagged inline-math island
    (:mod:`brailix.core.inline_math`) the frontend converts later.

    ``<w:object>`` elements containing a MathType / Equation 3.0 OLE
    object are extracted from ``ole_blobs`` and — because MTEF is binary,
    which the text IR can't carry — decoded through the MTEF adapter here
    into an eager ``$<math>...</math>$`` island.

    Word EQ fields (``<w:fldChar begin>`` + ``<w:instrText>eq ...</w:instrText>``
    + ``<w:fldChar end>``) span multiple runs; an :class:`_FieldState`
    instance threads the in-flight ``instrText`` buffer across run
    boundaries so the complete instruction is captured (and likewise
    deferred, as an ``eq_field`` island).

    Runs carrying ``<w:vertAlign>`` (the super/subscript a user sets via
    Ctrl+Shift+= / Ctrl+=) are not text that can be flattened away: a
    coalescing pass turns each maximal cluster of script-bearing runs into
    a linearised ``script_cluster`` island. Building the MathML and judging
    whether the cluster is chemistry happen in the frontend adapter;
    ``chem_detection`` only selects the chem-enabled source name — see
    :func:`_coalesce_script_clusters`.
    """
    if ole_blobs is None:
        ole_blobs = {}
    tokens = _iter_paragraph_tokens(p, ole_blobs)
    yield from _coalesce_script_clusters(tokens, chem_detection=chem_detection)


def _iter_paragraph_tokens(p: Element, ole_blobs: dict[str, bytes]):
    """Lower a ``<w:p>`` into a flat token stream for the coalescer.

    Each token is one of:

    * ``("text", str, vert)``  — run text, ``vert`` ∈ ``{None, "super",
      "sub"}`` from the run's ``<w:vertAlign>``;
    * ``("math", str)`` — an already-formed inline-math island, opaque to
      script coalescing: a deferred source-tagged island (inline OMML / EQ
      field) or an eager ``$<math>...$`` one (OLE MTEF);
    * ``("block", MathBlock)`` — a standalone display equation.

    This is the old body of :func:`_walk_paragraph_content`, re-expressed
    so the run-level vertical-alignment survives down to the coalescer
    instead of being flattened into bare text.
    """
    field_state = _FieldState()
    # Iterate top-level children only — ``.iter()`` would re-visit nested
    # elements once their parent has handled them. Each child is dispatched by
    # :func:`_emit_child_tokens`, which transparently recurses through
    # run-container wrappers (revision tracking, content controls, smart tags)
    # so their inline math / scripts survive instead of being scraped to text.
    for child in p:
        yield from _emit_child_tokens(child, ole_blobs, field_state)
    # A field still open at paragraph end never reached its `end`: its
    # instruction was never assembled and its visible-fallback text was held
    # back. Flush that text so an unclosed or cross-paragraph field doesn't
    # silently swallow the rest of the paragraph (the formula itself can't be
    # recovered without its `end`, but the visible text must not vanish).
    if field_state.in_field:
        leftover = field_state.take_unclosed_result()
        if leftover:
            yield ("text", leftover, None)


# Run-container wrappers Word places around ordinary inline content. They carry
# no content of their own — their children are runs / math / nested wrappers
# and must be walked the same way, never flattened to bare ``<w:t>`` text.
_TRANSPARENT_RUN_WRAPPERS = frozenset(
    {"ins", "del", "moveFrom", "moveTo", "smartTag", "customXml"}
)


def _emit_child_tokens(child: Element, ole_blobs, field_state):
    """Yield paragraph tokens for one direct child of a ``<w:p>`` (or of a
    transparent run-container wrapper).

    Factored out of :func:`_iter_paragraph_tokens` so revision-tracking
    (``<w:ins>`` / ``<w:del>`` / ``<w:moveFrom>`` / ``<w:moveTo>``),
    content-control (``<w:sdt>``), smart-tag and custom-XML wrappers can
    recurse through the *same* dispatch. Word emits ordinary runs — including
    inline ``<m:oMath>`` islands, ``<w:object>`` OLE math and run
    ``<w:vertAlign>`` scripts — inside these wrappers; the old text-only
    ``else`` scrape destroyed all of that (a tracked-changes insertion of a
    formula came out as bare literal text, an OLE equation vanished).
    """
    tag = _local(child.tag)
    if tag == "oMathPara":
        yield ("block", _math_block_from_omath_para(child))
    elif tag == "oMath":
        yield ("math", _inline_math_as_text(child))
    elif tag == "r":
        vert = _run_vert_align(child)
        for piece in _walk_run(child, ole_blobs, field_state):
            if _is_inline_math(piece):
                yield ("math", piece)
            else:
                yield ("text", piece, vert)
    elif tag == "hyperlink":
        # A hyperlink wraps ordinary runs / math — transparent to content.
        for hyper_child in child:
            yield from _emit_child_tokens(hyper_child, ole_blobs, field_state)
    elif tag == "object":
        text = _ole_object_to_inline_math(child, ole_blobs)
        if text:
            yield ("math", text)
    elif tag == "fldSimple":
        # Word's simple-field form: instruction in ``w:instr`` attribute,
        # cached result text as children. Skip the result (visual rendering).
        instr = _ns_attr(child, _W_PREFIX, "instr") or ""
        piece = _eq_field_to_inline_math(instr)
        if piece is not None:
            yield ("math", piece)
    elif tag == "AlternateContent":
        # Word wraps OLE objects in <mc:AlternateContent> when both a modern
        # (Choice) and legacy (Fallback) representation exist. Prefer Fallback
        # for OLE math — Choice is usually the picture preview we can't read.
        for piece, math in _walk_alternate_content(child, ole_blobs):
            if math is not None:
                yield ("block", math)
            elif piece:
                yield ("math", piece)
    elif tag in _TRANSPARENT_RUN_WRAPPERS:
        # Revision tracking / smart tag / custom XML: recurse into the inline
        # content the wrapper carries.
        for sub in child:
            yield from _emit_child_tokens(sub, ole_blobs, field_state)
    elif tag == "sdt":
        # Structured-document tag (content control): inline content lives under
        # <w:sdtContent>; <w:sdtPr> / <w:sdtEndPr> are properties, skip them.
        content = _first_local(child, "sdtContent")
        if content is not None:
            for sub in content:
                yield from _emit_child_tokens(sub, ole_blobs, field_state)
    elif tag == "pPr":
        # Paragraph properties — already consumed by style / list detection.
        return
    else:
        # Genuinely unknown wrapping element: descend transparently through the
        # SAME dispatch as the named run wrappers, so inline math / OLE / EQ
        # fields / vertAlign scripts under an unrecognised wrapper survive
        # instead of being flattened to bare <w:t> text (which also dropped the
        # vertical-alignment context). In well-formed OOXML <w:t> always lives
        # inside a <w:r>, which the 'r' branch above walks; property sub-trees
        # (rPr/pPr/...) recurse to nothing, so this stays safe.
        for sub in child:
            yield from _emit_child_tokens(sub, ole_blobs, field_state)


# ---------------------------------------------------------------------------
# Run-level vertical alignment → inline math (Ctrl+= / Ctrl+Shift+= scripts)
# ---------------------------------------------------------------------------

# Word's ``w:val`` for a raised / lowered run. ``baseline`` (and a missing
# element) is ordinary text.
_VERT_ALIGN = {"superscript": "super", "subscript": "sub"}

# Half-width operators that may glue a formula together inside a script
# cluster — the cluster alphabet, alongside ASCII alphanumerics. Operator
# canonicalisation and the cluster → MathML build (with chemistry detection)
# now live in the frontend ``script_cluster`` adapter; this layer only
# gathers the cluster and linearises it.
_CLUSTER_OPS = frozenset("+-()[]")


def _run_vert_align(r: Element) -> str | None:
    """Return ``"super"`` / ``"sub"`` for a run carrying ``<w:vertAlign>``.

    Word writes ``<w:rPr><w:vertAlign w:val="superscript|subscript"/>``
    when text is raised / lowered via the Ctrl+Shift+= / Ctrl+= shortcuts
    (or the Font dialog). ``"baseline"`` and the absence of the element
    both mean ordinary text → ``None``.
    """
    rpr = _first_local(r, "rPr")
    if rpr is None:
        return None
    va = _first_local(rpr, "vertAlign")
    if va is None:
        return None
    val = _ns_attr(va, _W_PREFIX, "val")
    return _VERT_ALIGN.get(val or "")


def _is_inline_math(piece: str) -> bool:
    """True for an already-formed inline-math island (so the coalescer
    treats it as an opaque unit, never script text).

    Covers both forms a paragraph token can carry: a deferred
    source-tagged island (inline OMML / EQ field, converted later by the
    frontend) and the eagerly-built ``$<math>...</math>$`` form still used
    by the MTEF / script-cluster paths.
    """
    return inline_math.is_tagged(piece) or (
        piece.startswith(_INLINE_MATH_OPEN) and piece.endswith("$")
    )


def _is_cluster_char(ch: str) -> bool:
    """A character that may join a sub/superscript cluster: ASCII letters /
    digits and the handful of half-width operators that hold a formula
    together. Whitespace, CJK, and prose punctuation are boundaries — they
    end a cluster so the surrounding prose stays prose."""
    return ch.isascii() and (ch.isalnum() or ch in _CLUSTER_OPS)


def _coalesce_script_clusters(tokens, *, chem_detection: bool = False):
    """Turn the token stream from :func:`_iter_paragraph_tokens` back into
    ``(text_piece, math_block)`` pairs, folding every cluster of
    script-bearing run text into one deferred ``script_cluster`` island.

    Consecutive ``text`` tokens accumulate; an inline-math island or a
    display block flushes them. Flushing renders the buffered text,
    replacing each maximal run of cluster characters that contains at
    least one script with inline math (:func:`_render_text_with_scripts`).
    Inline pieces are concatenated into a single text yield (matching the
    old per-paragraph join) with a guard space inserted between two
    abutting ``$...$`` islands so the segmenter's inline-math regex — which
    rejects ``$$`` — still sees each one.
    """
    inline: list[str] = []
    text_buf: list[tuple[str, str | None]] = []

    def append_inline(part: str) -> None:
        if part and inline and inline[-1].endswith("$") and part.startswith("$"):
            inline.append(" ")
        if part:
            inline.append(part)

    def flush_text() -> None:
        if text_buf:
            append_inline(
                _render_text_with_scripts(text_buf, chem_detection=chem_detection)
            )
            text_buf.clear()

    def take_inline() -> str:
        combined = "".join(inline)
        inline.clear()
        return combined

    for tok in tokens:
        kind = tok[0]
        if kind == "text":
            text_buf.append((tok[1], tok[2]))
        elif kind == "math":
            flush_text()
            append_inline(tok[1])
        elif kind == "block":
            flush_text()
            combined = take_inline()
            if combined:
                yield combined, None
            yield "", tok[1]
    flush_text()
    combined = take_inline()
    if combined:
        yield combined, None


def _render_text_with_scripts(
    buf: list[tuple[str, str | None]], *, chem_detection: bool
) -> str:
    """Render buffered ``(text, vert)`` tokens, replacing script clusters
    with inline math and leaving everything else as literal text.

    The tokens are expanded to ``(char, vert)`` — whitespace forced to the
    baseline so it always breaks a cluster — then scanned into maximal runs
    of cluster characters. A run holding at least one script char becomes
    inline math; plain runs and non-cluster characters pass through
    unchanged.
    """
    chars: list[tuple[str, str | None]] = []
    for text, vert in buf:
        for ch in text:
            chars.append((ch, None if ch.isspace() else vert))

    out: list[str] = []
    i = 0
    n = len(chars)
    while i < n:
        ch, vert = chars[i]
        if vert is None and not _is_cluster_char(ch):
            out.append(ch)
            i += 1
            continue
        j = i
        has_script = False
        while j < n:
            cj, vj = chars[j]
            if vj is None and not _is_cluster_char(cj):
                break
            if vj is not None:
                has_script = True
            j += 1
        run = chars[i:j]
        if has_script:
            out.append(_cluster_to_inline_math(run, chem_detection=chem_detection))
        else:
            out.append("".join(c for c, _ in run))
        i = j
    return "".join(out)


def _cluster_to_inline_math(
    run: list[tuple[str, str | None]], *, chem_detection: bool
) -> str:
    """Encode one Word script cluster as a deferred inline-math island.

    The cluster — formatted-text sub/superscripts like ``x²`` / ``H₂O`` — is
    *linearised* to a compact ``base ^{..} _{..}`` source string and wrapped
    as a source-tagged island (:mod:`brailix.core.inline_math`). Building the
    MathML, and judging whether the cluster is chemistry, is the frontend's
    job: the ``script_cluster`` adapter does it later (ARCHITECTURE §1). The
    ``chem_detection`` *config* selects the source name; the chemical
    *judgment* itself runs in the adapter, not here.
    """
    source = "script_cluster_chem" if chem_detection else "script_cluster"
    return inline_math.wrap(source, _linearise_cluster(run))


def _linearise_cluster(run: list[tuple[str, str | None]]) -> str:
    """Linearise a script cluster to a ``base ^{..} _{..}`` source string.

    Baseline characters pass through; a maximal superscript run becomes
    ``^{...}`` and a subscript run ``_{...}``. The cluster alphabet (ASCII
    alphanumerics plus ``+-()[]``) never contains ``^`` / ``_`` / ``{`` /
    ``}``, so no escaping is needed and the frontend ``script_cluster``
    adapter parses it back unambiguously.
    """
    parts: list[str] = []
    i, n = 0, len(run)
    while i < n:
        ch, vert = run[i]
        if vert is None:
            parts.append(ch)
            i += 1
            continue
        j = i
        while j < n and run[j][1] == vert:
            j += 1
        chunk = "".join(c for c, _ in run[i:j])
        parts.append(("^{" if vert == "super" else "_{") + chunk + "}")
        i = j
    return "".join(parts)


# ---------------------------------------------------------------------------
# Word field state machine (EQ fields span multiple runs)
# ---------------------------------------------------------------------------


class _FieldState:
    """In-flight state for ``<w:fldChar>`` / ``<w:instrText>`` parsing.

    A Word field looks like::

        <w:r><w:fldChar w:fldCharType="begin"/></w:r>
        <w:r><w:instrText>eq \\f(1,2)</w:instrText></w:r>
        <w:r><w:fldChar w:fldCharType="separate"/></w:r>   ← optional
        <w:r><w:t>cached visible result</w:t></w:r>        ← skipped
        <w:r><w:fldChar w:fldCharType="end"/></w:r>

    The instruction text accumulates between ``begin`` and
    ``separate`` (or ``end`` if no separate). After ``separate`` we're
    in the cached-result section, which we discard because the
    authoritative content is the instruction itself. Nested fields are
    supported via ``depth``; only depth-1 EQ instructions are
    converted (nested ones are part of the outer instruction text).
    """

    __slots__ = ("depth", "after_separate", "instr_buf", "result_buf")

    def __init__(self) -> None:
        self.depth: int = 0
        self.after_separate: bool = False
        self.instr_buf: list[str] = []
        # Visible-fallback text buffered while in the cached-result section.
        # Discarded on a normal `end` (so it never doubles converted math),
        # but flushed by the paragraph walker if the field is left unclosed.
        self.result_buf: list[str] = []

    @property
    def in_field(self) -> bool:
        return self.depth > 0

    @property
    def collecting_instr(self) -> bool:
        """True iff we're inside a field but before its ``separate`` marker."""
        return self.depth > 0 and not self.after_separate

    @property
    def in_cached_result(self) -> bool:
        """True iff inside a field's cached-result (visible-fallback) section
        — after ``separate``, before ``end``."""
        return self.depth > 0 and self.after_separate

    def begin(self) -> None:
        if self.depth == 0:
            self.instr_buf = []
            self.result_buf = []
            self.after_separate = False
        self.depth += 1

    def separate(self) -> None:
        if self.depth > 0:
            self.after_separate = True

    def end(self) -> str | None:
        """Close one field level. Returns the assembled instruction
        text if a top-level field just closed, else None."""
        if self.depth == 0:
            return None
        self.depth -= 1
        if self.depth == 0:
            instr = "".join(self.instr_buf)
            self.instr_buf = []
            # A normally-closed field's visible fallback is discarded — the
            # instruction (e.g. converted EQ math) is the authoritative form.
            self.result_buf = []
            self.after_separate = False
            return instr
        return None

    def add_instr(self, text: str) -> None:
        if self.collecting_instr:
            self.instr_buf.append(text)

    def add_result(self, text: str) -> None:
        if self.in_cached_result:
            self.result_buf.append(text)

    def take_unclosed_result(self) -> str:
        """Drain the buffered visible-fallback text of a field left open at
        paragraph end (unclosed, or whose ``end`` lands in a later
        paragraph), so it is recovered as text instead of silently eaten."""
        text = "".join(self.result_buf)
        self.result_buf = []
        return text


def _eq_field_to_inline_math(instr: str) -> str | None:
    """Encode an EQ field ``instr`` as a deferred ``eq_field`` island.

    Returns ``None`` for non-EQ fields (HYPERLINK, PAGE, TOC, …) so the
    caller can skip them silently. The "is this an EQ field?" gate stays
    here (input-side), but the EQ→MathML conversion is *deferred*: the
    raw instruction is wrapped as a source-tagged island
    (:func:`brailix.core.inline_math.wrap`) for the frontend's math pass
    to convert, so this module takes no math-frontend dependency. The EQ
    adapter wraps its own parse failures in ``<merror>``, so a malformed
    equation still surfaces as inline math (with a MATH_ERROR warning).
    """
    text = instr.strip()
    if not text:
        return None
    # Field code is the first whitespace-delimited word.
    head = text.split(None, 1)[0].lower()
    if head != "eq":
        return None
    return inline_math.wrap("eq_field", text)


def _walk_run(
    r: Element,
    ole_blobs: dict[str, bytes],
    field_state: _FieldState | None = None,
):
    """Yield text pieces inside a ``<w:r>``, including any OLE objects.

    Word commonly nests ``<w:object>`` inside a run when the equation
    is inline with text. Returning a list keeps the caller's
    ``(text, math)`` contract intact — every yielded piece is a string
    that gets appended to the surrounding paragraph text.

    ``field_state`` (when provided) tracks ``w:fldChar`` boundaries
    across runs so EQ fields whose instruction spans multiple runs
    still parse correctly. Text inside the field's cached-result
    section (between ``separate`` and ``end``) is silently dropped so
    Word's visible-text fallback doesn't end up duplicated alongside
    the converted math.
    """
    parts: list[str] = []
    for child in r:
        tag = _local(child.tag)
        if tag == "fldChar":
            if field_state is None:
                continue
            ftype = _ns_attr(child, _W_PREFIX, "fldCharType")
            if ftype == "begin":
                field_state.begin()
            elif ftype == "separate":
                field_state.separate()
            elif ftype == "end":
                instr = field_state.end()
                if instr is not None:
                    piece = _eq_field_to_inline_math(instr)
                    if piece is not None:
                        parts.append(piece)
            continue
        if tag == "instrText":
            if field_state is not None and field_state.collecting_instr:
                field_state.add_instr(child.text or "")
            continue
        if field_state is not None and field_state.in_cached_result:
            # Inside the field's cached-result (visible-fallback) section.
            # Buffer it rather than dropping outright: a normally-closing
            # field discards this on `end` (so it never doubles the converted
            # math), but an unclosed field — no `end`, or an `end` in a later
            # paragraph — flushes it back at paragraph end instead of
            # silently eating the rest of the paragraph.
            if tag == "t":
                field_state.add_result(child.text or "")
            elif tag == "br":
                field_state.add_result("\n")
            elif tag == "tab":
                field_state.add_result(" ")
            continue
        if tag == "t":
            parts.append(child.text or "")
        elif tag == "br":
            parts.append("\n")
        elif tag == "tab":
            parts.append(" ")
        elif tag == "object":
            text = _ole_object_to_inline_math(child, ole_blobs)
            if text:
                parts.append(text)
        elif tag == "AlternateContent":
            for piece, math in _walk_alternate_content(child, ole_blobs):
                if math is not None:
                    # A display equation (oMathPara) in a run-nested
                    # AlternateContent comes back as ("", MathBlock). _walk_run
                    # yields string pieces, so fold the display block in as an
                    # inline-math island (mirrors _convert_table_cell) rather
                    # than discard the _math slot and silently lose the formula.
                    parts.append(inline_math.wrap(math.source, math.text or ""))
                elif piece:
                    parts.append(piece)
    yield from parts


def _walk_alternate_content(
    alt: Element, ole_blobs: dict[str, bytes]
):
    """Walk an ``<mc:AlternateContent>`` for math content.

    Strategy: try Fallback first — that's where Word stores the legacy
    ``<w:object>`` form when also offering a modern drawing in Choice.
    Choice is descended only if Fallback yields nothing.
    """
    fallback = _first_local(alt, "Fallback")
    if fallback is not None:
        pieces = list(_walk_alt_subtree(fallback, ole_blobs))
        # Short-circuit Choice only when Fallback yielded *real* content. An
        # empty placeholder run yields ("", None), which used to set produced=
        # True and suppress Choice — silently dropping a formula that lived
        # only in Choice. Consumers filter empty pieces, so yielding them is
        # harmless; the decision must hinge on whether any was non-empty.
        if any(piece or math is not None for piece, math in pieces):
            yield from pieces
            return
    for choice in alt:
        if _local(choice.tag) == "Choice":
            yield from _walk_alt_subtree(choice, ole_blobs)


def _walk_alt_subtree(
    node: Element,
    ole_blobs: dict[str, bytes],
    field_state: _FieldState | None = None,
):
    """Descend into an AlternateContent branch, surfacing math content.

    The branch can be any depth — Word sometimes nests another
    ``<w:r>`` or ``<w:p>`` here. We dispatch through the same machinery
    used by paragraph walking, just without the paragraph-level
    splitting (the caller's run/paragraph context already has that).

    Note: this re-implements the object / oMath / oMathPara / r tag
    dispatch of :func:`_iter_paragraph_tokens` (different return contract —
    ``(piece, math)`` here vs. tokens there). A new inline-math source added
    to that walker must be mirrored here, or AlternateContent branches will
    silently drop it.

    A single ``_FieldState`` is threaded through the whole branch (created at
    the top-level call, passed down through recursion) so a cross-run EQ field
    — ``fldChar begin`` / ``instrText`` / ``end`` spread over separate runs —
    assembles instead of being dropped (``_walk_run`` skips ``fldChar`` when no
    state is passed). Unclosed text is flushed at the branch end, matching the
    paragraph walker.
    """
    if field_state is None:
        field_state = _FieldState()
        own_state = True
    else:
        own_state = False
    for child in node:
        tag = _local(child.tag)
        if tag == "object":
            text = _ole_object_to_inline_math(child, ole_blobs)
            if text:
                yield text, None
        elif tag == "oMath":
            yield _inline_math_as_text(child), None
        elif tag == "oMathPara":
            yield "", _math_block_from_omath_para(child)
        elif tag == "r":
            for piece in _walk_run(child, ole_blobs, field_state):
                yield piece, None
        else:
            # Recurse — the OLE might be wrapped in another shape /
            # drawing element we don't directly handle.
            yield from _walk_alt_subtree(child, ole_blobs, field_state)
    if own_state and field_state.in_field:
        leftover = field_state.take_unclosed_result()
        if leftover:
            yield leftover, None


def _math_block_from_omath_para(node: Element) -> MathBlock:
    """Wrap a standalone display equation in a :class:`MathBlock`.

    The block carries the raw OMML XML; the math frontend's OMML
    adapter does the conversion at Pipeline time. Keeping the
    conversion lazy here (rather than pre-MathML'ing) keeps the input
    layer's job simple — "extract structure", not "translate dialects".
    """
    omml_xml = _serialize(node)
    return MathBlock(source="omml", text=omml_xml)


# ---------------------------------------------------------------------------
# Style + list info
# ---------------------------------------------------------------------------


def _paragraph_style(p: Element) -> str | None:
    """Read ``w:pPr/w:pStyle@w:val`` — the paragraph style name.

    Returns the raw style id Word stored (e.g. ``"Heading1"``). The
    heading detector matches both ``"Heading 1"`` and ``"Heading1"``
    via :data:`_HEADING_STYLE_RE`.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is None:
        return None
    style = _first(pPr, _W_PREFIX + "pStyle")
    if style is None:
        return None
    # Qualified ``w:val`` first, bare ``val`` fallback — same two-step every
    # other OOXML attribute read here uses. Some emitters drop the prefix on
    # pStyle@val; reading only the qualified form silently lost heading/list
    # detection (the style name came back None, so the paragraph degraded to
    # plain body text).
    return _ns_attr(style, _W_PREFIX, "val")


# OOXML ``w:jc@w:val`` → the alignments braille layout can act on. Word
# 2013+ writes the LTR-relative ``start`` / ``end``; older files use
# ``left`` / ``right``. Only ``center`` and ``right`` (and ``end``, right's
# relative spelling) map to something — ``left`` / ``start`` are the default
# and ``both`` (justified) / ``distribute`` / the kashida variants have no
# braille convention, so all of those are absent and fall through to ``None``.
_JC_ALIGN = {
    "center": "center",
    "right": "right",
    "end": "right",
}


def _paragraph_alignment(p: Element) -> str | None:
    """Return the braille-relevant alignment of ``<w:p>``, or ``None``.

    Reads ``w:pPr/w:jc@w:val`` and maps it through :data:`_JC_ALIGN`. Only
    ``center`` and ``right`` survive — the two horizontal placements braille
    layout has a convention for. ``left`` / ``start`` (the default) and
    ``both`` / ``distribute`` (no braille analogue) all yield ``None``, so
    the paragraph reads flush-left exactly like untagged prose and no align
    marker is carried needlessly.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is None:
        return None
    jc = _first(pPr, _W_PREFIX + "jc")
    if jc is None:
        return None
    val = _ns_attr(jc, _W_PREFIX, "val")
    return _JC_ALIGN.get((val or "").lower())


def _ilvl_value(ilvl_elem: Element | None) -> int:
    """Parse ``w:ilvl@w:val`` to a 0-based list level, defaulting to 0.

    Tolerates a missing element, a missing / blank ``val`` (some emitters
    write a bare ``val`` with no ``w:`` prefix — mirror the ``or .get("val")``
    fallback used elsewhere here), and a non-integer value. None of those
    should crash list detection; the old ``int(ilvl_elem.get(...))`` raised
    ``TypeError`` on a missing or bare ``val``.
    """
    if ilvl_elem is None:
        return 0
    raw = _ns_attr(ilvl_elem, _W_PREFIX, "val")
    if not raw:
        return 0
    try:
        return max(0, int(raw))
    except ValueError:
        return 0


def _paragraph_list_info(
    p: Element, *, style: str | None = None
) -> tuple[int, bool] | None:
    """Return ``(level, ordered)`` if the paragraph is a list item,
    else ``None``.

    Two signals are accepted:

    * ``w:pPr/w:numPr`` — real Word numbering. The ``ilvl`` element
      gives the nesting depth; the ``numId`` → ``abstractNumId`` →
      ``lvl`` / ``numFmt`` chain in ``word/numbering.xml`` would tell
      us ordered vs unordered, but resolving that is out of scope for
      this V1.  Default to unordered.
    * ``w:pPr/w:pStyle`` named one of Word's built-in list styles
      (``ListBullet``, ``ListNumber``, ``ListNumber2``, ``ListDash``,
      ``ListParagraph``, ``ListContinue``).  python-docx applies these
      without creating a numPr, so we have to look at the style name
      to recognise them.

    The pStyle-only path is the common case for documents written by
    python-docx; the numPr path is the common case for documents
    edited in Word.  Either way the braille renderer treats list
    items uniformly — item position drives the marker, not visual
    style — so the approximate ordered detection here is harmless.
    """
    pPr = _first(p, _W_PREFIX + "pPr")
    if pPr is not None:
        numPr = _first(pPr, _W_PREFIX + "numPr")
        if numPr is not None:
            ilvl_elem = _first(numPr, _W_PREFIX + "ilvl")
            return _ilvl_value(ilvl_elem), False
    if style:
        m = _LIST_STYLE_RE.match(style)
        if m:
            family = m.group(1).lower()
            depth = int(m.group(2)) if m.group(2) else 1
            ordered = family == "number"
            return max(0, depth - 1), ordered
    return None


# ---------------------------------------------------------------------------
# Table
# ---------------------------------------------------------------------------


def _convert_table(
    tbl: Element,
    *,
    ole_blobs: dict[str, bytes] | None = None,
    chem_detection: bool = False,
) -> Table:
    rows: list[TableRow] = []
    # Descend transparently through revision-tracking / content-control
    # wrappers, the same way the body walker does — a row or cell wrapped in
    # <w:ins> (inserted) or <w:sdt> (content control) is common in real
    # "accept-changes-first" documents and would otherwise be silently
    # dropped, leaving the braille table missing whole rows / cells.
    for tr in _iter_effective_body_children(tbl):
        if _local(tr.tag) != "tr":
            continue
        cells: list[TableCell] = []
        for tc in _iter_effective_body_children(tr):
            if _local(tc.tag) != "tc":
                continue
            cells.append(
                _convert_table_cell(
                    tc, ole_blobs=ole_blobs, chem_detection=chem_detection
                )
            )
        if cells:
            rows.append(TableRow(cells=cells))
    return Table(rows=rows)


def _convert_table_cell(
    tc: Element,
    *,
    ole_blobs: dict[str, bytes] | None = None,
    chem_detection: bool = False,
) -> TableCell:
    """Flatten a cell's paragraphs into one TableCell text.

    The braille table renderer expects flat cell text (no nested
    paragraphs); we join paragraph contents with a newline so a
    multi-paragraph cell still preserves the visual break. A nested
    table inside the cell is flattened the same way — its inner cells'
    text is folded in rather than dropped.
    """
    parts: list[str] = []
    # Same transparent descent as _convert_table: a paragraph or nested table
    # wrapped in <w:ins> / <w:sdt> inside a cell must not be dropped.
    for child in _iter_effective_body_children(tc):
        tag = _local(child.tag)
        if tag == "p":
            paragraph_blocks = _convert_paragraph(
                child, ole_blobs=ole_blobs, chem_detection=chem_detection
            )
            for blk in paragraph_blocks:
                if isinstance(blk, MathBlock):
                    # Fold a display MathBlock into the cell as inline math:
                    # tables are visually constrained, display math doesn't
                    # fit. Deferred like every other inline OMML — emit a
                    # source-tagged island (carrying the block's own source
                    # dialect) for the frontend's math pass to convert.
                    parts.append(inline_math.wrap(blk.source, blk.text or ""))
                else:
                    parts.append(blk.text or "")
        elif tag == "tbl":
            # Nested table: the braille cell renderer wants flat text, so
            # fold the inner grid's cells into this cell (each inner cell
            # is one newline-separated chunk) instead of dropping them.
            nested = _convert_table(
                child, ole_blobs=ole_blobs, chem_detection=chem_detection
            )
            for row in nested.rows:
                for inner_cell in row.cells:
                    if inner_cell.text:
                        parts.append(inner_cell.text)
    return TableCell(text="\n".join(p for p in parts if p))
